### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by VishaPatil** [appmattus/kotlinfixture#107]

**Comment by VishaPatil** [comment]
Hello,

I noticed no new releases in last couple years. So wanted to confirm the status of this project.

Best,
Vishal

**Comment by mattmook** [comment]
I still use the project a lot myself, just haven't found the time to keep its dependencies up to date, although am in the process of doing this currently. So perhaps more unloved rather than anything else.

**Comment by morbic** [comment]
Hi @mattmook, anything changed regarding dependencies? I can see the open PRs unmerged, do you have any time to review and accept community help?
