### ISSUE TITLE
Make PopulateInstance interface public to make creating new resolvers easier

### ISSUE THREAD

**Issue by DeafLight** [appmattus/kotlinfixture#49]
Hi,

First of all, thanks for this nice and promising library :slightly_smiling_face: 

I'd like to create a variant of `ClassResolver` in order to apply the default constructor strategy that is used in this library's honorable .NET cousin, [AutoFixture](https://github.com/AutoFixture/AutoFixture). Unlike the random approach you chose in your `ClassResolver`, it will use the constructor with the fewest parameters as explained [here](https://blog.ploeh.dk/2011/04/19/ConstructorstrategiesforAutoFixture/).

I was about to simply duplicate the `ClassResolver` class, but unfortunately `PopulateInstance` interface is internal, making it impossible to use it directly. Is there a reason for that ? Wouldn't it be useful to make it public in order to allow this kind of customizations ?

Or is there another way to achieve that that I missed ?

Thanks

**Comment by mattmook** [comment]
I assume it makes sense to make the ordering user configurable, as it is in AutoFixture, with the ability to select `modest`, `greedy`, `random` and of course your own ordering (should you wish). I should be able to get something added in to do this pretty quickly in the next day or so.

There was no particular reason `PopulateInstance` is internal other than hiding the internals of the library, and the general lack of documentation on things like this!

**Comment by mattmook** [comment]
I've added in a constructor strategy to support this functionality in v0.9.2:

```
val fixture = kotlinFixture {
     constructorStrategy(ModestConstructorStrategy)
 }
```

**Comment by DeafLight** [comment]
That's really nice, thank you !
