### ISSUE TITLE
How to apply NeverNullStrategy on list Items

### ISSUE THREAD

**Issue by Alton09** [appmattus/kotlinfixture#75]
The documentation [here](https://github.com/appmattus/kotlinfixture/blob/main/fixture/configuration-options.adoc#overriding-nullability-with-nullabilitystrategy) specifies that you can ensure all generated values are non null. I tried using this when generating a list of `Trail` objects to ensure that none of the trail element properties would be null. Also, I'm referencing this library in an Android instrumentation test.

Here is what my fixture configuration looks like:
```kotlin
private val fixture = kotlinFixture {
    nullabilityStrategy(NeverNullStrategy)
}
private val trails = fixture<List<Trail>>()
```

Here is the `Trail` class:
```kotlin
data class Trail(
    val name: String? = null,
    var username: String? = null,
    val startLatitude: Double? = null,
    val startLongitude: Double? = null,
    val endLatitude: Double? = null,
    val endLongitude: Double? = null,
    val description: String? = null,
    val city: String? = null,
    val state: String? = null,
    val distance: Double? = null
)
```
Here's a screenshot showing that some values are null:
![Screen Shot 2020-11-20 at 9 43 39 AM](https://user-images.githubusercontent.com/2661383/99825900-e2d6cb80-2b14-11eb-9137-ff0da5ccff4f.png)

Am I missing something in the configuration to make this work properly? Thanks! 

This library is great by the way :)

**Comment by Alton09** [comment]
I've also confirmed that `NeverNullStrategy` does not work when populating each element in a lit with `fixture()` shown in the snippet below:
```kotlin
private val trails = listOf<Trail>(fixture(), fixture(), fixture())
```

**Comment by mattmook** [comment]
The issue comes as you have both null types and default values. So while the null strategy will ensure it won't generate a null at random, the optional strategy will randomly choose between generating a value or using the default value.

What this means is for this scenario you also need to override the optionalStrategy to be NeverOptionalStrategy:

```
private val fixture = kotlinFixture {
    nullabilityStrategy(NeverNullStrategy)
    optionalStrategy(NeverOptionalStrategy)
}
```

**Comment by Alton09** [comment]
Thanks for the response @mattmook ! Yep, just confirmed that I was missing `optionalStrategy(NeverOptionalStrategy)`. It is working correctly now!
