### ISSUE TITLE
How to return generic type for a fixture to return a fixture with configuration builder properties ?

### ISSUE THREAD

**Issue by istvandesign** [appmattus/kotlinfixture#81]
Hello, I tried to return a kotlinFixture in a function with ConfigurationBuilder, but I discovered that I have no idea what type it will return.

Is there any way to return the correct type for 

`private fun myReusableFixture(): Sometype = kotlinFixture { 
   property(X::y) { y } }
`

It will complain when used as fun fixture() = myReusableFixture() and then fixture() in the every mockk.

I want to return the same fake values in multiple tests, now it generates a new fake value that I have no reference to.

**Comment by mattmook** [comment]
`kotlinFixture { ... }` returns a `com.appmattus.kotlinfixture.Fixture`. The `Fixture` class and its configuration is immutable and stateless by nature.

As a function you'd need to call it as `myReusableFixture()()`. However, there's nothing stopping you storing your shared configuration in a top-level `val`:

```kotlin
private val myReusableFixture = kotlinFixture { property(X::y) { y } }
```

Regardless of whether this is a `fun` or `val` you will always get different values back when calling `myReusableFixture <Type>()` as it is random by nature.

To mitigate this the easiest suggestion for when you need to refer to one of the values is to create the needed instance outside of your mock, so something like this:

```kotlin
@Test
fun myTest {
    // If a lot of your tests are generating the same fixture this could be generated as a class member instead
    val outcome = myReusableFixture<Outcome>()

    val car = mockk<Car>()
    every { car.drive(Direction.NORTH) } returns outcome

    ...
}
```
