### ISSUE TITLE
Generating customised objects

### ISSUE THREAD

**Issue by juliabirkett** [appmattus/kotlinfixture#82]
This is not an issue, it's more of a question.

I'm trying to generate `Strings` with a specific length but I couldn't understand how's the easiest way to do it using this library.
This is just one example and the necessity makes sense IMHO. It's a trivial use case but I don't see any similar examples in the docs nor in the tests.
Can anyone show me how?

**Comment by mattmook** [comment]
hi @juliabirkett

Probably the simplest mechanism is to override with a string factory:

```
            val fixture = kotlinFixture {
                factory<String> {
                    val alphanumeric = ('A'..'Z') + ('a'..'z') + ('0'..'9')
                    buildString {
                        repeat(20) { append(alphanumeric.random(random)) }
                    }
                }
            }

            val randomAlphanumericString = fixture<String>()
```

NOTE: I'm passing `random` to `random()` so if you ever initialised fixture with a seeded random this factory will use that seeded random too. It's not strictly necessary as its unlikely to cause any issues, just more correct.

An alternative is to use the [generex module](https://github.com/appmattus/kotlinfixture/tree/main/fixture-generex) and define a regex for the generation; the readme for the module contains a string example.
